language: bash

services:
  - docker

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - docker build -t pdftotext .
  - docker run -d -p 8080:80 pdftotext
  - docker ps -a

script:
  - bats test/server.bats
